### ISSUE TITLE
Detach/Attach not working as expected.

### ISSUE THREAD

**Issue by Matt-Owens** [ysuzuki1603/BottomNavigation#1]
The conditionals in MainActivity.kt are not firing ever.

if (fragment.isAdded)
and
if (fragment.isDetached)

This results in the fragment always being added, even when it was previously deattached and should be re-attached.

Any idea what is causing this behavior?

**Comment by yasszu** [comment]
Thank you for announcing. It was a bug as you said. It is need to get Fragment with findFragmentById before detaching/attaching Fragments. I have already fixed this bug. Please check   #2.

**Comment by yasszu** [comment]
Thank you for announcing. It was a bug as you said. It is need to get Fragment with findFragmentByTag before detaching/attaching Fragments. I have already fixed this bug. Please check #2.

**Comment by Matt-Owens** [comment]
Good catch!  Works great now.  Thanks so much for this great example.
